# 1. ??????? Port (??? 8082 ???????? Port 8080 ?????????????)
server:
  port: 8082

spring:
  application:
    name: Metric

  # 2. (????????) ?????????? "prod" ????????????????????
  profiles:
    active: prod

  servlet:
    multipart:
      max-file-size: 10MB

# 3. ?????????? JWT (??????????)
application:
  security:
    jwt:
      secret-key: 74ba7cadbef37e73106b951a5c86313c957215f8175f66060daacc073c3c41c231df2b96058eceee511b82985322d9092ed7dd770f071bfa2bfc3bb89c8c868b
      expiration: 86400000
      refresh-token:
        expiration: 604800000

---

# 4. (?????) ??????????????????? Atlas
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      # ?????? URI ??? Atlas ???????????
      uri: mongodb+srv://kengchayodom:viRY8LNB7e58y8Zu@metric.cikp7hx.mongodb.net/?appName=Metric

      # ?????????????????
      database: gam_shop